project_id = "uxaxgrdxikvligkjyyxz"

[functions.comments]
verify_jwt = false

[functions.chainhook-contracts]
verify_jwt = false

[functions.cleanup-sessions]
verify_jwt = false

[functions.atproto-auth]
verify_jwt = false

[functions.add-contract]
verify_jwt = false